import { DEFAULT_ANIMATION_EDITOR_STATE, clearAnimationSelection, reconcileAnimationEditorState, requestFrameSelected, selectAnimationBone, setAnimationEditorAutoKey, setAnimationEditorOrientation, setAnimationEditorTime, setAnimationEditorTool, setAnimationEditorViewPreset } from '../modes/animation/AnimationEditorState';
interface Result{name:string;passed:boolean;error?:string}const assert=(c:unknown,m:string)=>{if(!c)throw new Error(m)};const test=async(name:string,fn:()=>void|Promise<void>):Promise<Result>=>{try{await fn();return{name,passed:true}}catch(error){return{name,passed:false,error:error instanceof Error?error.message:String(error)}}};
export async function runAnimationEditorStateTests():Promise<{passed:number;total:number}>{const results:Result[]=[];
results.push(await test('selection is shared by stable rig and bone ids',()=>{const s=selectAnimationBone(DEFAULT_ANIMATION_EDITOR_STATE,'rig','bone');assert(s.selection?.rigId==='rig'&&s.selection.boneId==='bone','selection mismatch');assert(!clearAnimationSelection(s).selection,'selection should clear')}));
results.push(await test('timeline time is finite non-negative and reconciles to project duration',()=>{let s=setAnimationEditorTime(DEFAULT_ANIMATION_EDITOR_STATE,12);s=reconcileAnimationEditorState(s,[],5);assert(s.time===5,'time must clamp to duration');let rejected=false;try{setAnimationEditorTime(s,Number.NaN)}catch{rejected=true}assert(rejected,'NaN time must reject')}));
results.push(await test('selection reconciliation removes deleted rig or bone',()=>{const s=selectAnimationBone(DEFAULT_ANIMATION_EDITOR_STATE,'rig','gone');const r=reconcileAnimationEditorState(s,[{rigId:'rig',boneId:'kept'}],10);assert(!r.selection,'stale selection must clear')}));
results.push(await test('authoring controls live in the same editor state',()=>{let s=setAnimationEditorAutoKey(DEFAULT_ANIMATION_EDITOR_STATE,true);s=setAnimationEditorTool(s,'TRANSLATE');s=setAnimationEditorOrientation(s,'LOCAL');s=setAnimationEditorViewPreset(s,'FRONT');assert(s.autoKey&&s.poseTool==='TRANSLATE'&&s.orientation==='LOCAL'&&s.viewPreset==='FRONT','authoring controls mismatch')}));
results.push(await test('frame-selected requests are monotonic',()=>{const a=requestFrameSelected(DEFAULT_ANIMATION_EDITOR_STATE),b=requestFrameSelected(a);assert(a.frameSelectedToken===1&&b.frameSelectedToken===2,'frame token must increment')}));
for(const r of results)console.log(`${r.passed?'✓':'✗'} [${r.passed?'PASS':'FAIL'}] ${r.name}${r.error?` — ${r.error}`:''}`);return{passed:results.filter(r=>r.passed).length,total:results.length};}
