import { ViewportGestureController } from '../modes/animation/ViewportGestureController';
interface Result{name:string;passed:boolean;error?:string}
const assert=(c:unknown,m:string)=>{if(!c)throw new Error(m)};
const test=async(name:string,fn:()=>void|Promise<void>):Promise<Result>=>{try{await fn();return{name,passed:true}}catch(error){return{name,passed:false,error:error instanceof Error?error.message:String(error)}}};
export async function runAnimationGestureControllerTests():Promise<{passed:number;total:number}>{const results:Result[]=[];
results.push(await test('second pointer cancels the original single-pointer owner before multi-touch starts',()=>{const events:string[]=[];const c=new ViewportGestureController({onSingleStart:id=>events.push(`start:${id}`),onSingleEnd:(id,cancelled)=>events.push(`end:${id}:${cancelled}`),onMultiStart:()=>events.push('multi')});c.pointerDown(4,{x:0,y:0});c.pointerDown(9,{x:100,y:0});assert(events.join('|')==='start:4|end:4:true|multi',`unexpected arbitration: ${events.join('|')}`)}));
results.push(await test('multi-touch emits pinch and pan through controller callbacks',()=>{let scale=0,pan={x:0,y:0};const c=new ViewportGestureController({onMultiMove:(s,p)=>{scale=s;pan=p}});c.pointerDown(1,{x:0,y:0});c.pointerDown(2,{x:100,y:0});c.pointerMove(2,{x:120,y:20});assert(scale>0&&pan.x===10&&pan.y===10,'multi callback mismatch')}));
results.push(await test('multi-to-single exit reports rebased remaining pointer',()=>{let remaining:number|undefined;const c=new ViewportGestureController({onMultiEnd:id=>remaining=id});c.pointerDown(3,{x:0,y:0});c.pointerDown(8,{x:100,y:0});c.pointerEnd(8);assert(remaining===3&&c.snapshot.mode==='SINGLE'&&c.snapshot.primaryId===3,'remaining pointer was not rebased')}));
results.push(await test('pointer cancel ends active single interaction as cancelled',()=>{let cancelled=false;const c=new ViewportGestureController({onSingleEnd:(_id,c)=>{cancelled=c}});c.pointerDown(2,{x:0,y:0});c.pointerEnd(2,true);assert(cancelled&&c.snapshot.mode==='IDLE','cancel must teardown interaction')}));
for(const r of results)console.log(`${r.passed?'✓':'✗'} [${r.passed?'PASS':'FAIL'}] ${r.name}${r.error?` — ${r.error}`:''}`);return{passed:results.filter(r=>r.passed).length,total:results.length};}
