import { solveTwoBoneIK } from '../modes/animation/IKSolver';
import { aimBoneQuaternion, quaternionFromTo } from '../modes/animation/QuaternionAim';
import { evaluateRigWorldTransforms, rotateByQuaternion } from '../modes/animation/RigTransformEvaluator';
import { beginTransformGizmoDrag, snapTransformDelta, transformGizmoDelta } from '../modes/animation/TransformGizmoController';
import type { AnimationRig } from '../types/creative';

interface Result { name: string; passed: boolean; error?: string }
function assert(condition: unknown, message: string): void { if (!condition) throw new Error(message); }
function near(a: number, b: number, epsilon = 1e-6): boolean { return Math.abs(a - b) <= epsilon; }
function nearVec(a: [number, number, number], b: [number, number, number], epsilon = 1e-6): boolean { return near(a[0], b[0], epsilon) && near(a[1], b[1], epsilon) && near(a[2], b[2], epsilon); }
async function test(name: string, fn: () => void | Promise<void>): Promise<Result> { try { await fn(); return { name, passed: true }; } catch (error) { return { name, passed: false, error: error instanceof Error ? error.message : String(error) }; } }
const pose = (position: [number, number, number] = [0, 0, 0], rotation: [number, number, number] = [0, 0, 0]) => ({ position, rotation, scale: [1, 1, 1] as [number, number, number] });

export async function runAnimationRigMathTests(): Promise<{ passed: number; total: number }> {
  const results: Result[] = [];
  results.push(await test('Quaternion aim maps the native +Y bone axis onto target direction', () => { const q=aimBoneQuaternion([0,0,0],[1,0,0]); assert(q,'aim quaternion missing'); assert(nearVec(rotateByQuaternion([0,1,0],q!),[1,0,0]),'unexpected aimed direction'); }));
  results.push(await test('Quaternion from-to handles anti-parallel vectors deterministically', () => { const q=quaternionFromTo([0,1,0],[0,-1,0]); assert(q,'anti-parallel quaternion missing'); assert(nearVec(rotateByQuaternion([0,1,0],q!),[0,-1,0]),'anti-parallel rotation failed'); }));
  results.push(await test('Two-bone IK preserves maximum reach for a distant target', () => { const s=solveTwoBoneIK({root:[0,0,0],target:[10,0,0],upperLength:2,lowerLength:3}); assert(!s.reachable,'distant target should be unreachable'); assert(near(Math.hypot(...s.end),5),'end must clamp to maximum chain reach'); assert(near(Math.hypot(...s.joint),2),'upper bone length changed'); }));
  results.push(await test('Two-bone IK preserves minimum reach for a near target', () => { const s=solveTwoBoneIK({root:[0,0,0],target:[.1,0,0],upperLength:3,lowerLength:1}); assert(!s.reachable,'near target should be unreachable'); assert(near(Math.hypot(...s.end),2),'end must clamp to minimum chain reach'); }));
  results.push(await test('Pole target controls the IK bend side', () => { const a=solveTwoBoneIK({root:[0,0,0],target:[3,0,0],pole:[0,1,0],upperLength:2,lowerLength:2}),b=solveTwoBoneIK({root:[0,0,0],target:[3,0,0],pole:[0,-1,0],upperLength:2,lowerLength:2}); assert(a.joint[1]>0&&b.joint[1]<0,'pole target should flip bend plane'); }));
  results.push(await test('Rig hierarchy composes parent quaternion into connected child world transform', () => { const rig:AnimationRig={id:'rig',name:'Rig',objectId:'object',bones:[{id:'root',name:'Root',length:2,connected:false,ikFk:'FK',pose:pose([0,0,0],[0,0,Math.PI/2])},{id:'child',name:'Child',parentId:'root',length:1,connected:true,ikFk:'FK',pose:pose()}]}; const w=evaluateRigWorldTransforms(rig); assert(nearVec(w.bones.root.tail,[-2,0,0]),'root tail mismatch'); assert(nearVec(w.bones.child.head,w.bones.root.tail),'connected child must start at parent tail'); assert(nearVec(w.bones.child.tail,[-3,0,0]),'child did not inherit parent orientation'); }));
  results.push(await test('Rig evaluator rejects hierarchy cycles', () => { const rig:AnimationRig={id:'cycle',name:'Cycle',objectId:'object',bones:[{id:'a',name:'A',parentId:'b',length:1,connected:true,ikFk:'FK',pose:pose()},{id:'b',name:'B',parentId:'a',length:1,connected:true,ikFk:'FK',pose:pose()}]}; let rejected=false;try{evaluateRigWorldTransforms(rig)}catch{rejected=true}assert(rejected,'cycle must be rejected explicitly'); }));
  results.push(await test('Projected translation follows the camera-projected gizmo axis', () => { const d=beginTransformGizmoDrag('TRANSLATE','x',{x:10,y:20},80,Math.PI/360,{x:3,y:4}); assert(near(transformGizmoDelta(d,{x:70,y:100}),1),'projected translation should use normalized screen axis'); }));
  results.push(await test('Rotation arc returns wrapped angular displacement around projected pivot', () => { const d=beginTransformGizmoDrag('ROTATE','z',{x:100,y:50},80,Math.PI/360,undefined,{x:50,y:50}); assert(near(transformGizmoDelta(d,{x:50,y:100}),Math.PI/2),'quarter arc should equal PI/2'); }));
  results.push(await test('Rotation arc remains continuous across the ±PI boundary', () => { const c={x:0,y:0},a=Math.PI-0.1,b=-Math.PI+0.1,d=beginTransformGizmoDrag('ROTATE','z',{x:Math.cos(a)*100,y:Math.sin(a)*100},80,Math.PI/360,undefined,c),v=transformGizmoDelta(d,{x:Math.cos(b)*100,y:Math.sin(b)*100}); assert(near(v,.2,1e-5),`wrapped arc should be 0.2, got ${v}`); }));
  results.push(await test('Rotation near pivot falls back to linear pointer mapping', () => { const d=beginTransformGizmoDrag('ROTATE','x',{x:3,y:0},80,.01,{x:1,y:0},{x:0,y:0}); assert(near(transformGizmoDelta(d,{x:13,y:0}),.1),'near-pivot rotation should use safe linear fallback'); }));
  results.push(await test('Transform snapping is deterministic for positive and negative deltas', () => { assert(near(snapTransformDelta(.26,.1),.3),'positive snap mismatch'); assert(near(snapTransformDelta(-.26,.1),-.3),'negative snap mismatch'); }));
  results.push(await test('Transform gizmo rejects invalid finite inputs and snap steps', () => { let badPoint=false,badStep=false;try{beginTransformGizmoDrag('TRANSLATE','x',{x:Number.NaN,y:0})}catch{badPoint=true}try{snapTransformDelta(1,0)}catch{badStep=true}assert(badPoint&&badStep,'invalid inputs must be rejected'); }));
  for(const r of results)console.log(`${r.passed?'✓':'✗'} [${r.passed?'PASS':'FAIL'}] ${r.name}${r.error?` — ${r.error}`:''}`);return{passed:results.filter(r=>r.passed).length,total:results.length};
}
