import { audibleMusicTracks, envelopeTimes, estimateTrackMeter, estimateTrackPeak, evaluateAutomationLane, moveNote, musicStepDuration, normalizeArrangement, normalizeAutomationLane, normalizeMusicProject, normalizeSFXPatch, notesForClip, quantizeNoteEvent, resizeNote, transposeNotes } from '../creative/AudioWorkspace';
import { createCreativeWorkspaceId, migrateLegacyCreativeDocument } from '../creative/CreativeDocumentFactory';
import { CreativeDocumentKernel } from '../creative/CreativeDocumentKernel';
import { createStudioStateCommand } from '../creative/useCreativeStudioDocument';
import type { MioMusicProject, MioSFXPatch, MusicTrack, SFXLayer } from '../types/creative';
interface Result{name:string;passed:boolean;error?:string} const assert=(c:unknown,m:string):void=>{if(!c)throw new Error(m)}; const test=async(name:string,run:()=>void|Promise<void>):Promise<Result>=>{try{await run();return{name,passed:true}}catch(error){return{name,passed:false,error:error instanceof Error?error.message:String(error)}}};
const musicTrack=(id:string,overrides:Partial<MusicTrack>={}):MusicTrack=>({id,name:id,role:'Melody',instrument:'synth_lead',volume:.8,pan:0,mute:false,solo:false,notes:[],...overrides});
const sfxLayer=():SFXLayer=>({id:'fx',name:'FX',type:'transient',waveType:'sine',baseFrequency:440,frequencySweep:220,attack:.1,decay:.2,sustain:.5,release:.4,filterCutoff:2000,filterResonance:2,distortion:.3,delayTime:.2,delayFeedback:.4,reverbMix:.25,volume:.8});
export async function runCreativeAudioWorkspaceTests():Promise<{passed:number;total:number}>{const results:Result[]=[];
results.push(await test('Music solo and mute routing selects only audible tracks',()=>{const tracks=[musicTrack('a'),musicTrack('b',{solo:true}),musicTrack('c',{solo:true,mute:true})];assert(audibleMusicTracks(tracks).map(t=>t.id).join(',')==='b','solo routing');assert(musicStepDuration(120)===.125,'tempo math');}));
results.push(await test('SFX ADSR envelope remains ordered inside short patch duration',()=>{const t=envelopeTimes({...sfxLayer(),attack:1,decay:1,release:1},2,.2);assert(t.attack<t.decay&&t.decay<=t.sustain&&t.sustain<t.end,'envelope order');}));
results.push(await test('Audio edits persist through shared undo and redo',()=>{const name='Audio.miosfx',sfx:MioSFXPatch={name:'Audio',category:'UI',duration:1,layers:[sfxLayer()]};const k=new CreativeDocumentKernel(migrateLegacyCreativeDocument(name,sfx,10,createCreativeWorkspaceId(name)));k.execute({command:createStudioStateCommand(k.snapshot(),name,{...sfx,layers:[{...sfx.layers[0],distortion:.8}]} as MioSFXPatch)});k.undo();assert((k.snapshot().metadata.legacyData as MioSFXPatch).layers[0].distortion===.3,'undo failed');}));
results.push(await test('Music authoring helpers quantize transpose and meter safely',()=>{const n=quantizeNoteEvent({id:'n',pitch:60.4,startStep:3,durationSteps:3,velocity:1.4},2,16);assert(n.startStep===4&&n.durationSteps===4&&n.velocity===1,'quantize');assert(transposeNotes([n],80)[0].pitch===127,'transpose');const p=normalizeMusicProject({tempo:999,key:'C',scale:'Major',totalSteps:16,tracks:[musicTrack('lead',{volume:2,notes:[n,{...n,id:'dup'}]})]});assert(p.tempo===300&&p.tracks[0].notes.length===1,'normalize');assert(estimateTrackPeak(p.tracks[0])===1&&estimateTrackMeter(p.tracks[0]).peak===1,'meter');}));
results.push(await test('Piano roll move and resize transactions stay inside project bounds',()=>{const n={id:'n',pitch:60,startStep:12,durationSteps:4,velocity:.8};const moved=moveNote(n,10,80,16);assert(moved.startStep===12&&moved.pitch===127,'move bounds');assert(resizeNote({...n,startStep:14},8,16).durationSteps===2,'resize bounds');}));
results.push(await test('Arrangement clips normalize and expand reusable loop material deterministically',()=>{const track=musicTrack('lead',{notes:[{id:'a',pitch:60,startStep:0,durationSteps:1,velocity:.8},{id:'b',pitch:64,startStep:2,durationSteps:1,velocity:.8}]});const arr=normalizeArrangement({totalSteps:32,clips:[{id:'c',trackId:'lead',name:'Verse',startStep:4,lengthSteps:8,sourceStartStep:0,loop:true},{id:'bad',trackId:'missing',name:'Bad',startStep:0,lengthSteps:4,sourceStartStep:0,loop:false}]},['lead']);assert(arr.clips.length===1,'dangling clip');const notes=notesForClip(track,arr.clips[0]);assert(notes.length===4&&notes[0].startStep===4&&notes[2].startStep===7,'loop expansion');}));
results.push(await test('SFX patch and automation lanes clamp and interpolate safely',()=>{const normalized=normalizeSFXPatch({name:'Unsafe',category:'IMPACT',duration:999,layers:[{...sfxLayer(),baseFrequency:-1,delayFeedback:2}]});assert(normalized.duration===60&&normalized.layers[0].baseFrequency===20&&normalized.layers[0].delayFeedback===.85,'patch bounds');const lane=normalizeAutomationLane({layerId:'fx',parameter:'filterCutoff',points:[{time:1,value:4000},{time:0,value:-2},{time:1,value:9000}]},2);assert(lane.points.length===2&&lane.points[0].value===20,'lane normalize');assert(evaluateAutomationLane(lane,.5,100)===2010,'lane interpolation');}));
for(const r of results)console.log(`${r.passed?'✓':'✗'} [${r.passed?'PASS':'FAIL'}] ${r.name}${r.error?` — ${r.error}`:''}`);return{passed:results.filter(r=>r.passed).length,total:results.length};}
