import { alignGraphicLayers, beginGraphicDrag, distributeGraphicLayers, graphicToMotionProject, hitTestGraphicLayers, nudgeGraphicLayers, snapGraphicPosition, toggleGraphicSelection, updateGraphicDrag, beginGraphicPenPath, appendGraphicPenPoint, finishGraphicPenPath, getGraphicPathSegments, splitGraphicPathSegment, insertGraphicPathPointOnSegment } from '../creative/GraphicMotionWorkspace';
import type { MioGraphicDocument } from '../types/creative';

interface Result { name:string; passed:boolean; error?:string }
const assert=(condition:unknown,message:string):void=>{if(!condition)throw new Error(message);};
const test=async(name:string,run:()=>void|Promise<void>):Promise<Result>=>{try{await run();return{name,passed:true};}catch(error){return{name,passed:false,error:error instanceof Error?error.message:String(error)}}};

const document:MioGraphicDocument={width:600,height:400,backgroundColor:'#000',layers:[
 {id:'a',name:'A',type:'shape',shapeType:'rectangle',visible:true,locked:false,opacity:1,x:13,y:20,width:100,height:50,fill:'#fff'},
 {id:'b',name:'B',type:'text',visible:true,locked:false,opacity:.8,x:240,y:80,width:120,height:40,fill:'#eee',text:'Mio',fontSize:24},
 {id:'c',name:'C',type:'shape',shapeType:'circle',visible:true,locked:false,opacity:1,x:480,y:140,width:60,height:60,fill:'#0ff'},
]};

export async function runGraphicMotionWorkspaceTests():Promise<{passed:number;total:number}>{
 const results:Result[]=[];
 results.push(await test('graphic alignment is deterministic',()=>{const next=alignGraphicLayers(document,['a','b'],'left');assert(next.layers[0].x===next.layers[1].x,'left alignment failed');}));
 results.push(await test('graphic distribution preserves endpoints',()=>{const next=distributeGraphicLayers(document,['a','b','c'],'horizontal');assert(next.layers[0].x===13&&next.layers[2].x===480,'distribution moved endpoints');}));
 results.push(await test('graphic grid snapping is bounded to grid increments',()=>{assert(snapGraphicPosition(13,8)===16,'grid snap failed');assert(snapGraphicPosition(13,8,false)===13,'disabled snap changed value');}));
 results.push(await test('graphic to motion bridge keeps editable vector/text semantics',()=>{const motion=graphicToMotionProject(document,8,24);assert(motion.layers.length===3,'bridge dropped editable layers');assert(motion.layers[1].type==='text'&&motion.layers[1].text==='Mio','text semantics lost');assert(motion.duration===8&&motion.fps===24,'motion settings lost');}));
 results.push(await test('pointer hit testing respects visual z-order',()=>{const hits=hitTestGraphicLayers(document,{x:250,y:90});assert(hits[0]==='b','topmost hit was not returned first');}));
 results.push(await test('multi-selection toggles deterministically',()=>{assert(toggleGraphicSelection(['a'],'b',true).join(',')==='a,b','additive select failed');assert(toggleGraphicSelection(['a','b'],'a',true).join(',')==='b','toggle deselect failed');}));
 results.push(await test('drag transaction moves unlocked layers with grid snap',()=>{const session=beginGraphicDrag(document,['a','b'],{x:0,y:0},8,true);const next=updateGraphicDrag(document,session,{x:10,y:10});assert(next.layers[0].x===24&&next.layers[0].y===32,'snapped drag failed');}));
 results.push(await test('keyboard nudge protects locked layers',()=>{const locked={...document,layers:document.layers.map(l=>l.id==='b'?{...l,locked:true}:l)};const next=nudgeGraphicLayers(locked,['a','b'],2,-1);assert(next.layers[0].x===15&&next.layers[1].x===240,'nudge lock boundary failed');}));
 results.push(await test('pen lifecycle creates appends and finishes open path',()=>{const started=beginGraphicPenPath(document,{x:40,y:50},'pen_test');assert(started.layerId==='pen_test','pen layer id unstable');const appended=appendGraphicPenPoint(started.document,started.layerId,{x:80,y:90});const finished=finishGraphicPenPath(appended.document,started.layerId,false),layer=finished.layers.find(l=>l.id===started.layerId);assert(layer?.path?.points.length===2,'pen append failed');assert(layer?.path?.closed===false,'open finish closed path');}));
 results.push(await test('pen close requires at least three anchors',()=>{const started=beginGraphicPenPath(document,{x:10,y:10},'pen_close');const two=appendGraphicPenPoint(started.document,started.layerId,{x:20,y:20}).document;assert(finishGraphicPenPath(two,started.layerId,true).layers.at(-1)?.path?.closed===false,'two-point path closed');const three=appendGraphicPenPoint(two,started.layerId,{x:30,y:10}).document;assert(finishGraphicPenPath(three,started.layerId,true).layers.at(-1)?.path?.closed===true,'three-point path did not close');}));
 results.push(await test('segment split preserves straight geometry',()=>{const started=beginGraphicPenPath(document,{x:0,y:0},'split_test');const appended=appendGraphicPenPoint(started.document,started.layerId,{x:100,y:0});const layer=appended.document.layers.find(l=>l.id===started.layerId);if(!layer?.path)throw new Error('split path missing');const segment=getGraphicPathSegments(layer.path)[0];if(!segment)throw new Error('segment missing');const split=splitGraphicPathSegment(segment,.5,'split_test_new');assert(Math.abs(split.point.x-50)<1e-9&&Math.abs(split.point.y)<1e-9,'split midpoint incorrect');assert(split.from.outX===0&&split.to.inX===100,'straight endpoint controls changed');}));
 results.push(await test('segment insertion is blocked on locked layers',()=>{const started=beginGraphicPenPath(document,{x:0,y:0},'locked_insert');const appended=appendGraphicPenPoint(started.document,started.layerId,{x:100,y:0});const locked={...appended.document,layers:appended.document.layers.map(l=>l.id===started.layerId?{...l,locked:true}:l)};const next=insertGraphicPathPointOnSegment(locked,started.layerId,0,.5);const layer=next.layers.find(l=>l.id===started.layerId);assert(layer?.path?.points.length===2,'locked layer was mutated');}));
 results.push(await test('invalid segment insertion is a no-op',()=>{const started=beginGraphicPenPath(document,{x:0,y:0},'invalid_insert');const appended=appendGraphicPenPoint(started.document,started.layerId,{x:100,y:0});const before=appended.document.layers.find(l=>l.id===started.layerId);const next=insertGraphicPathPointOnSegment(appended.document,started.layerId,99,.5),after=next.layers.find(l=>l.id===started.layerId);assert(after?.path?.points.length===before?.path?.points.length,'invalid segment mutated path');}));
 results.push(await test('closed path exposes and inserts on closing segment',()=>{const started=beginGraphicPenPath(document,{x:0,y:0},'closed_insert');const a=appendGraphicPenPoint(started.document,started.layerId,{x:100,y:0});const b=appendGraphicPenPoint(a.document,started.layerId,{x:100,y:100});const closed=finishGraphicPenPath(b.document,started.layerId,true);const layer=closed.layers.find(l=>l.id===started.layerId);if(!layer?.path)throw new Error('closed path missing');const segments=getGraphicPathSegments(layer.path);assert(segments.length===3&&segments[2].closing,'closing segment missing');const next=insertGraphicPathPointOnSegment(closed,started.layerId,2,.5),nextLayer=next.layers.find(l=>l.id===started.layerId);assert(nextLayer?.path?.points.length===4&&nextLayer.path.closed,'closing insertion failed');}));
 for(const result of results)console.log(`${result.passed?'✓':'✗'} [${result.passed?'PASS':'FAIL'}] ${result.name}${result.error?` — ${result.error}`:''}`);
 return {passed:results.filter(r=>r.passed).length,total:results.length};
}
