import type { MioMeshData } from '../types/creative';
import { canonicalMeshEdgeId,createCubeMesh } from '../modes/studio3d/modeling/MeshTopology';
import { loopCutMesh } from '../modes/studio3d/modeling/MeshLoopCut';
import { executeUnifiedBevel,MeshUnifiedBevelPreviewSession } from '../modes/studio3d/modeling/MeshUnifiedBevel';
import { diagnoseMeshTopology } from '../modes/studio3d/modeling/MeshTopologyDiagnostics';
interface R{name:string;passed:boolean;error?:string}const assert=(c:unknown,m:string)=>{if(!c)throw new Error(m)};const test=async(name:string,run:()=>void|Promise<void>):Promise<R>=>{try{await run();return{name,passed:true}}catch(e){return{name,passed:false,error:e instanceof Error?e.message:String(e)}}};
const bipyramid=():MioMeshData=>({vertices:[{id:'t',position:[0,0,1]},{id:'b',position:[0,0,-1]},{id:'a',position:[1,0,0]},{id:'c',position:[-0.5,0.866,0]},{id:'d',position:[-0.5,-0.866,0]}],faces:[{id:'tac',vertexIds:['t','a','c']},{id:'tcd',vertexIds:['t','c','d']},{id:'tda',vertexIds:['t','d','a']},{id:'bca',vertexIds:['b','c','a']},{id:'bdc',vertexIds:['b','d','c']},{id:'bad',vertexIds:['b','a','d']}]});
const network=()=>[canonicalMeshEdgeId('t','a'),canonicalMeshEdgeId('t','c'),canonicalMeshEdgeId('t','d'),canonicalMeshEdgeId('a','b'),canonicalMeshEdgeId('c','b'),canonicalMeshEdgeId('d','b')];
export async function runMeshUnifiedBevelTests():Promise<{passed:number;total:number}>{const rs:R[]=[];
rs.push(await test('unifies segmented closed-loop bevel',()=>{const cut=loopCutMesh(createCubeMesh(),canonicalMeshEdgeId('v0','v1'),0.5);const r=executeUnifiedBevel(cut.mesh,cut.newLoopEdgeIds,{widthRatio:0.1,segments:3,profile:0.6,curvature:0.2});assert(r.strategy==='closed-loop','closed strategy');assert(r.bevelFaceIds.length===cut.newLoopEdgeIds.length*3,'segmented faces expected')}));
rs.push(await test('unifies segmented coordinated network',()=>{const source=bipyramid(),before=JSON.stringify(source);const r=executeUnifiedBevel(source,network(),{widthRatio:0.08,segments:2,profile:0.5,curvature:0.15});assert(r.strategy==='coordinated-network','network strategy');const d=diagnoseMeshTopology(r.mesh);assert(!d.nonManifoldEdgeIds.length&&!d.inconsistentWindingEdgeIds.length&&!d.zeroAreaFaceIds.length,'network topology clean');assert(JSON.stringify(source)===before,'source immutable')}));
rs.push(await test('preview is immutable and cancel exact',()=>{const source=bipyramid(),s=new MeshUnifiedBevelPreviewSession(source,network());const a=s.preview({widthRatio:0.06,segments:1,profile:0.5,curvature:0}),b=s.preview({widthRatio:0.1,segments:2,profile:0.7,curvature:0.2});assert(JSON.stringify(a.mesh)!==JSON.stringify(b.mesh),'preview parameters alter result');assert(JSON.stringify(s.cancel())===JSON.stringify(source),'cancel restores exact source')}));
for(const r of rs)console.log(`${r.passed?'✓':'✗'} [${r.passed?'PASS':'FAIL'}] ${r.name}${r.error?` — ${r.error}`:''}`);return{passed:rs.filter(r=>r.passed).length,total:rs.length}}
