import type { Mio3DObject, Mio3DScene } from '../types/creative';
import { createCubeMesh } from '../modes/studio3d/modeling/MeshTopology';
import { evaluateSceneObjectMesh } from '../modes/studio3d/modeling/MeshBooleanSceneBinding';
import { diagnoseMeshTopology } from '../modes/studio3d/modeling/MeshTopologyDiagnostics';

interface R{name:string;passed:boolean;error?:string}
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(message)};
const test=async(name:string,run:()=>void|Promise<void>):Promise<R>=>{try{await run();return{name,passed:true}}catch(error){return{name,passed:false,error:error instanceof Error?error.message:String(error)}}};
const object=(id:string,position:[number,number,number]=[0,0,0],scale:[number,number,number]=[1,1,1]):Mio3DObject=>({id,name:id,type:'custom',position,rotation:[0,0,0],scale,color:'#fff',metalness:0,roughness:0.5,wireframe:false,mesh:createCubeMesh(),modifiers:[]});
const scene=(objects:Mio3DObject[]):Mio3DScene=>({objects,camera:{position:[0,0,5],fov:50},lights:{ambientColor:'#000',ambientIntensity:1,directionalColor:'#fff',directionalIntensity:1}});
const safe=(mesh:ReturnType<typeof createCubeMesh>)=>{const d=diagnoseMeshTopology(mesh);return d.valid&&!d.boundaryEdgeIds.length&&!d.nonManifoldEdgeIds.length&&!d.zeroAreaFaceIds.length&&!d.inconsistentWindingEdgeIds.length&&!d.duplicateFaceGroups.length&&!d.isolatedVertexIds.length};

export async function runMeshBooleanModifierSceneTests(){const results:R[]=[];
results.push(await test('evaluates boolean modifier against translated scene operand without mutating scene',()=>{const a=object('a'),b=object('b',[0.5,0,0]);a.modifiers=[{id:'bool',type:'boolean',enabled:true,operation:'intersection',operandObjectId:'b'}];const s=scene([a,b]),before=JSON.stringify(s),result=evaluateSceneObjectMesh(s,'a').mesh,xs=result.vertices.map(vertex=>vertex.position[0]);assert(result.vertices.length===8&&result.faces.length===6,'intersection result box');assert(Math.min(...xs)===0&&Math.max(...xs)===0.5,'operand mapped into target local space');assert(safe(result),'result topology safe');assert(JSON.stringify(s)===before,'scene immutable')}));
results.push(await test('maps positive operand scale into target local space',()=>{const a=object('a'),b=object('b',[0.5,0,0],[0.5,1,1]);a.modifiers=[{id:'bool',type:'boolean',enabled:true,operation:'intersection',operandObjectId:'b'}];const result=evaluateSceneObjectMesh(scene([a,b]),'a').mesh,xs=result.vertices.map(vertex=>vertex.position[0]);assert(Math.min(...xs)===0.25&&Math.max(...xs)===0.5,'scaled operand bounds mapped correctly')}));
results.push(await test('rejects missing self and cyclic boolean operands explicitly',()=>{const missing=object('missing');missing.modifiers=[{id:'m',type:'boolean',enabled:true,operation:'union',operandObjectId:'ghost'}];let missingRejected=false;try{evaluateSceneObjectMesh(scene([missing]),'missing')}catch(error){missingRejected=String(error).includes('not found')}const self=object('self');self.modifiers=[{id:'s',type:'boolean',enabled:true,operation:'union',operandObjectId:'self'}];let selfRejected=false;try{evaluateSceneObjectMesh(scene([self]),'self')}catch(error){selfRejected=String(error).includes('cannot reference itself')}const a=object('a'),b=object('b');a.modifiers=[{id:'ab',type:'boolean',enabled:true,operation:'union',operandObjectId:'b'}];b.modifiers=[{id:'ba',type:'boolean',enabled:true,operation:'union',operandObjectId:'a'}];let cycleRejected=false;try{evaluateSceneObjectMesh(scene([a,b]),'a')}catch(error){cycleRejected=String(error).includes('cycle detected')}assert(missingRejected&&selfRejected&&cycleRejected,'invalid scene references rejected')}));
results.push(await test('rejects rotated operand until arbitrary orientation kernel exists',()=>{const a=object('a'),b=object('b');b.rotation=[0,0,0.25];a.modifiers=[{id:'bool',type:'boolean',enabled:true,operation:'union',operandObjectId:'b'}];let rejected=false;try{evaluateSceneObjectMesh(scene([a,b]),'a')}catch(error){rejected=String(error).includes('rotation-free')}assert(rejected,'rotated operand rejected explicitly')}));
for(const result of results)console.log(`${result.passed?'✓':'✗'} [${result.passed?'PASS':'FAIL'}] ${result.name}${result.error?` — ${result.error}`:''}`);
return{passed:results.filter(result=>result.passed).length,total:results.length};
}
