import { canonicalMeshEdgeId,createCubeMesh } from '../modes/studio3d/modeling/MeshTopology';
import { loopCutMesh } from '../modes/studio3d/modeling/MeshLoopCut';
import { evaluateMeshModifierStack } from '../modes/studio3d/modeling/MeshModifierStack';
import type { MioMeshData,MioMeshModifier } from '../types/creative';
interface R{name:string;passed:boolean;error?:string}const assert=(c:unknown,m:string)=>{if(!c)throw new Error(m)};const test=async(name:string,run:()=>void|Promise<void>):Promise<R>=>{try{await run();return{name,passed:true}}catch(e){return{name,passed:false,error:e instanceof Error?e.message:String(e)}}};
const half=():MioMeshData=>({vertices:[{id:'a',position:[0,-1,-1]},{id:'b',position:[1,-1,-1]},{id:'c',position:[1,1,-1]},{id:'d',position:[0,1,-1]},{id:'e',position:[0,-1,1]},{id:'f',position:[1,-1,1]},{id:'g',position:[1,1,1]},{id:'h',position:[0,1,1]}],faces:[{id:'back',vertexIds:['a','d','c','b']},{id:'front',vertexIds:['e','f','g','h']},{id:'bottom',vertexIds:['a','b','f','e']},{id:'top',vertexIds:['d','h','g','c']},{id:'outer',vertexIds:['b','c','g','f']}]});
export async function runMeshModifierStackTests(){const rs:R[]=[];
rs.push(await test('evaluates mirror without mutating authoritative source',()=>{const source=half(),before=JSON.stringify(source);const r=evaluateMeshModifierStack(source,[{id:'mirror',type:'mirror',enabled:true,axis:'x',merge:true,mergeDistance:1e-6}]);assert(r.mesh.vertices.length===12,'four plane vertices reused and four mirrored vertices added');assert(r.mesh.faces.length===10,'five mirrored faces added');assert(JSON.stringify(source)===before,'source immutable')}));
rs.push(await test('disabled modifiers are skipped in stable order',()=>{const source=createCubeMesh();const mods:MioMeshModifier[]=[{id:'off',type:'mirror',enabled:false,axis:'x',merge:false,mergeDistance:0},{id:'on',type:'mirror',enabled:true,axis:'y',merge:false,mergeDistance:0}];const r=evaluateMeshModifierStack(source,mods);assert(r.steps.length===1&&r.steps[0].modifierId==='on','only enabled modifier evaluated');assert(r.mesh.vertices.length===16,'full cube mirrored')}));
rs.push(await test('evaluates native Catmull-Clark subdivision without source mutation',()=>{const source=createCubeMesh(),before=JSON.stringify(source);const r=evaluateMeshModifierStack(source,[{id:'subd',type:'subdivision',enabled:true,levels:1}]);assert(r.mesh.vertices.length===26,'cube subdivision has 8 vertex + 12 edge + 6 face points');assert(r.mesh.faces.length===24,'cube subdivision produces 24 quads');assert(r.mesh.faces.every(f=>f.vertexIds.length===4),'all subdivided faces are quads');assert(JSON.stringify(source)===before,'source unchanged')}));
rs.push(await test('composes modifier order deterministically',()=>{const source=createCubeMesh();const r=evaluateMeshModifierStack(source,[{id:'mirror',type:'mirror',enabled:true,axis:'x',merge:false,mergeDistance:0},{id:'subd',type:'subdivision',enabled:true,levels:1}]);assert(r.steps.map(s=>s.type).join(',')==='mirror,subdivision','ordered evaluation preserved');assert(r.mesh.faces.length===48,'subdivision sees mirrored input')}));
rs.push(await test('composes Subdivision then Solidify',()=>{const source=createCubeMesh(),before=JSON.stringify(source);const r=evaluateMeshModifierStack(source,[{id:'subd',type:'subdivision',enabled:true,levels:1},{id:'solid',type:'solidify',enabled:true,thickness:0.1}]);assert(r.steps.map(s=>s.type).join(',')==='subdivision,solidify','ordered composition');assert(r.mesh.faces.length===48,'closed subdivided cube gets inner and outer shells');assert(JSON.stringify(source)===before,'source unchanged')}));
rs.push(await test('composes Solidify then Array',()=>{const source=createCubeMesh(),before=JSON.stringify(source);const r=evaluateMeshModifierStack(source,[{id:'solid',type:'solidify',enabled:true,thickness:0.1},{id:'array',type:'array',enabled:true,count:3,offset:[2,0,0]}]);assert(r.steps.map(s=>s.type).join(',')==='solidify,array','ordered composition');assert(r.mesh.faces.length===36,'solidified cube twelve faces times three');assert(JSON.stringify(source)===before,'source unchanged')}));
rs.push(await test('evaluates Bevel as final stack modifier',()=>{const cut=loopCutMesh(createCubeMesh(),canonicalMeshEdgeId('v0','v1'),0.5),source=cut.mesh,before=JSON.stringify(source);const r=evaluateMeshModifierStack(source,[{id:'bev',type:'bevel',enabled:true,widthRatio:0.08,segments:2,profile:0.5,curvature:0.1,edgeIds:cut.newLoopEdgeIds}]);assert(r.steps.length===1&&r.steps[0].type==='bevel','bevel evaluated');assert(r.mesh.faces.length>source.faces.length,'derived topology created');assert(JSON.stringify(source)===before,'source unchanged')}));
for(const r of rs)console.log(`${r.passed?'✓':'✗'} [${r.passed?'PASS':'FAIL'}] ${r.name}${r.error?` — ${r.error}`:''}`);return{passed:rs.filter(r=>r.passed).length,total:rs.length}}
