import type{AnimationInterpolation,Keyframe,MioAnimationProject}from'../../types/creative';
export interface KeyframeRef{trackId:string;keyId:string}
const finite=(n:number,name:string)=>{if(!Number.isFinite(n))throw new Error(`${name} must be finite`);return n};
let keySequence=0;
const createKeyId=(trackId:string,time:number)=>`key_${trackId}_${Math.round(time*1000000)}_${++keySequence}`;
const sameTime=(a:number,b:number)=>Math.abs(a-b)<1e-6;
export const ensureStableKeyframeIds=(project:MioAnimationProject):MioAnimationProject=>({...project,tracks:project.tracks.map(t=>({...t,keyframes:t.keyframes.map((k,i)=>k.id?k:{...k,id:`key_${t.id}_legacy_${i}`})}))});
const findKey=(keys:Keyframe[],id:string)=>keys.findIndex(k=>k.id===id);
export const insertNumericKeyframe=(project:MioAnimationProject,trackId:string,time:number,value:number,interpolation:AnimationInterpolation='easeInOut'):MioAnimationProject=>{finite(time,'time');finite(value,'value');const clamped=Math.max(0,Math.min(project.duration,time));return{...project,tracks:project.tracks.map(t=>{if(t.id!==trackId)return t;const existing=t.keyframes.find(k=>sameTime(k.time,clamped));if(existing)return{...t,keyframes:t.keyframes.map(k=>k.id===existing.id?{...k,value,interpolation}:k)};return{...t,keyframes:[...t.keyframes,{id:createKeyId(trackId,clamped),time:clamped,value,interpolation}].sort((a,b)=>a.time-b.time)}})}};
export const updateNumericKeyframe=(project:MioAnimationProject,ref:KeyframeRef,changes:{time?:number;value?:number;interpolation?:AnimationInterpolation}):MioAnimationProject=>({...project,tracks:project.tracks.map(t=>{if(t.id!==ref.trackId)return t;const index=findKey(t.keyframes,ref.keyId);if(index<0)return t;const nextTime=changes.time===undefined?t.keyframes[index].time:Math.max(0,Math.min(project.duration,finite(changes.time,'time')));const collision=t.keyframes.find((k,i)=>i!==index&&sameTime(k.time,nextTime));const updated={...t.keyframes[index],...changes,time:nextTime,value:changes.value===undefined?t.keyframes[index].value:finite(changes.value,'value')};return{...t,keyframes:t.keyframes.filter((_,i)=>i!==index&&(!collision||t.keyframes[i].id!==collision.id)).concat(updated).sort((a,b)=>a.time-b.time)}})});
export const deleteKeyframe=(project:MioAnimationProject,ref:KeyframeRef):MioAnimationProject=>({...project,tracks:project.tracks.map(t=>t.id!==ref.trackId?t:{...t,keyframes:t.keyframes.filter(k=>k.id!==ref.keyId)})});
