import React, { useEffect, useRef } from 'react';
import * as THREE from 'three';
import type { MioAnimationProject } from '../../types/creative';
import { evaluateAnimationProject } from './AnimationRuntime';
import { evaluateRigWorldTransforms } from './RigTransformEvaluator';
import type { PointerPoint } from './TransformGizmoController';

export interface Animation3DViewportProps {
  className?: string; project?: MioAnimationProject; time?: number; selectedRigId?: string; selectedBoneId?: string;
  onSelectBone?: (rigId: string, boneId: string) => void;
  onPoseDragStart?: (point: PointerPoint) => void; onPoseDrag?: (point: PointerPoint) => void; onPoseDragEnd?: () => void; onPoseDragCancel?: () => void;
}
interface BoneVisual { rigId: string; boneId: string; line: THREE.Line; head: THREE.Mesh; }
export const Animation3DViewport: React.FC<Animation3DViewportProps> = (props) => {
  const hostRef=useRef<HTMLDivElement>(null), propsRef=useRef(props); useEffect(()=>{propsRef.current=props},[props]);
  useEffect(()=>{
    const host=hostRef.current;if(!host)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x0d1117);const camera=new THREE.PerspectiveCamera(45,1,.01,1000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.style.cssText='width:100%;height:100%;touch-action:none';host.appendChild(renderer.domElement);
    scene.add(new THREE.HemisphereLight(0xbfdcff,0x18202c,2.1));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(4,7,5);scene.add(key);scene.add(new THREE.GridHelper(20,40,0x37516b,0x202d3b));const axes=new THREE.AxesHelper(1.25);axes.position.set(-2.5,.01,2.5);scene.add(axes);
    const rigGroup=new THREE.Group();scene.add(rigGroup);const visuals:BoneVisual[]=[];const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2();const normal=new THREE.LineBasicMaterial({color:0x78d7ff}),selectedLine=new THREE.LineBasicMaterial({color:0xffa24a}),joint=new THREE.MeshBasicMaterial({color:0x9be7ff}),selectedJoint=new THREE.MeshBasicMaterial({color:0xffa24a});
    const rebuild=()=>{while(rigGroup.children.length){const child=rigGroup.children[0];rigGroup.remove(child);if(child instanceof THREE.Mesh||child instanceof THREE.Line)child.geometry.dispose()}visuals.length=0;const current=propsRef.current.project;if(!current?.rigs?.length)return;const evaluated=evaluateAnimationProject(current,propsRef.current.time??current.currentTime);for(const rig of current.rigs){const local:Record<string,typeof rig.bones[number]['pose']>={};for(const b of rig.bones)local[b.id]=evaluated.bonePoses[`${rig.id}:${b.id}`]??b.pose;const world=evaluateRigWorldTransforms(rig,local);for(const boneId of world.order){const b=world.bones[boneId],isSelected=propsRef.current.selectedRigId===rig.id&&propsRef.current.selectedBoneId===boneId;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...b.head),new THREE.Vector3(...b.tail)]),isSelected?selectedLine:normal);line.userData={rigId:rig.id,boneId};const head=new THREE.Mesh(new THREE.SphereGeometry(isSelected?.09:.065,14,10),isSelected?selectedJoint:joint);head.position.set(...b.head);head.userData={rigId:rig.id,boneId};rigGroup.add(line,head);visuals.push({rigId:rig.id,boneId,line,head})}}};
    let azimuth=.64,elevation=.36,radius=7.8;const target=new THREE.Vector3(0,1.45,0);const updateCamera=()=>{const c=Math.cos(elevation);camera.position.set(target.x+radius*Math.sin(azimuth)*c,target.y+radius*Math.sin(elevation),target.z+radius*Math.cos(azimuth)*c);camera.lookAt(target)};updateCamera();
    const hitAt=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();ndc.set(((e.clientX-r.left)/r.width)*2-1,-((e.clientY-r.top)/r.height)*2+1);raycaster.setFromCamera(ndc,camera);return raycaster.intersectObjects(visuals.map(v=>v.head),false)[0]?.object};
    let pointerId:number|undefined,previousX=0,previousY=0,moved=false,poseDragging=false;
    const down=(e:PointerEvent)=>{if(e.pointerType==='mouse'&&e.button!==0)return;pointerId=e.pointerId;previousX=e.clientX;previousY=e.clientY;moved=false;const hit=hitAt(e);const selected=hit?.userData?.rigId===propsRef.current.selectedRigId&&hit?.userData?.boneId===propsRef.current.selectedBoneId;poseDragging=Boolean(selected&&propsRef.current.onPoseDragStart);if(hit?.userData?.rigId&&hit.userData?.boneId)propsRef.current.onSelectBone?.(hit.userData.rigId,hit.userData.boneId);if(poseDragging)propsRef.current.onPoseDragStart?.({x:e.clientX,y:e.clientY});renderer.domElement.setPointerCapture(e.pointerId)};
    const move=(e:PointerEvent)=>{if(e.pointerId!==pointerId)return;const dx=e.clientX-previousX,dy=e.clientY-previousY;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;previousX=e.clientX;previousY=e.clientY;if(poseDragging){propsRef.current.onPoseDrag?.({x:e.clientX,y:e.clientY});return}if(moved){azimuth-=dx*.008;elevation=THREE.MathUtils.clamp(elevation-dy*.008,-1.35,1.35);updateCamera()}};
    const end=(e:PointerEvent,cancel=false)=>{if(e.pointerId!==pointerId)return;if(poseDragging){cancel?propsRef.current.onPoseDragCancel?.():propsRef.current.onPoseDragEnd?.()}poseDragging=false;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);pointerId=undefined};
    const wheel=(e:WheelEvent)=>{e.preventDefault();radius=THREE.MathUtils.clamp(radius+e.deltaY*.008,2.5,24);updateCamera()};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',e=>end(e));renderer.domElement.addEventListener('pointercancel',e=>end(e,true));renderer.domElement.addEventListener('wheel',wheel,{passive:false});
    const resize=()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();let frame=0;const render=()=>{frame=requestAnimationFrame(render);rebuild();renderer.render(scene,camera)};render();
    return()=>{cancelAnimationFrame(frame);observer.disconnect();normal.dispose();selectedLine.dispose();joint.dispose();selectedJoint.dispose();renderer.dispose();renderer.domElement.remove()};
  },[]);
  return <div ref={hostRef} className={`absolute inset-0 overflow-hidden bg-[#0d1117] ${props.className??''}`} aria-label="3D animation viewport"/>;
};
