import type { MioMeshData,MioMeshFace } from '../../../types/creative';
import { deriveMeshEdges,validateMeshTopology } from './MeshTopology';
import { diagnoseMeshTopology } from './MeshTopologyDiagnostics';
type V=[number,number,number];const add=(a:V,b:V):V=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];const sub=(a:V,b:V):V=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];const cross=(a:V,b:V):V=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];const norm=(a:V):V=>{const l=Math.hypot(...a);return l>1e-12?[a[0]/l,a[1]/l,a[2]/l]:[0,0,0]};const scale=(a:V,s:number):V=>[a[0]*s,a[1]*s,a[2]*s];
const faceNormal=(f:MioMeshFace,v:Map<string,V>):V=>{let n:V=[0,0,0];for(let i=0;i<f.vertexIds.length;i++){const a=v.get(f.vertexIds[i])!,b=v.get(f.vertexIds[(i+1)%f.vertexIds.length])!;n=[n[0]+(a[1]-b[1])*(a[2]+b[2]),n[1]+(a[2]-b[2])*(a[0]+b[0]),n[2]+(a[0]-b[0])*(a[1]+b[1])]}return norm(n)};
export const solidifyMesh=(mesh:MioMeshData,thickness:number):MioMeshData=>{
 if(!Number.isFinite(thickness)||Math.abs(thickness)<=1e-8)throw new Error('Solidify thickness must be a non-zero finite number.');
 const validation=validateMeshTopology(mesh);if(!validation.valid)throw new Error(`Cannot solidify invalid mesh: ${validation.errors.join(' ')}`);
 const d=diagnoseMeshTopology(mesh);if(d.nonManifoldEdgeIds.length||d.inconsistentWindingEdgeIds.length)throw new Error('Solidify requires manifold consistently wound input.');
 const pos=new Map(mesh.vertices.map(v=>[v.id,v.position] as const)),normalSum=new Map<string,V>(mesh.vertices.map(v=>[v.id,[0,0,0] as V])),fn=new Map<string,V>();
 for(const f of mesh.faces){const n=faceNormal(f,pos);if(Math.hypot(...n)<=1e-12)throw new Error(`Face ${f.id} has no stable normal.`);fn.set(f.id,n);for(const id of f.vertexIds)normalSum.set(id,add(normalSum.get(id)!,n))}
 const half=thickness/2,vertices:MioMeshData['vertices']=[];for(const v of mesh.vertices){const n=norm(normalSum.get(v.id)!);if(Math.hypot(...n)<=1e-12)throw new Error(`Vertex ${v.id} has no stable normal.`);vertices.push({id:`${v.id}_solid_outer`,position:add(v.position,scale(n,half))},{id:`${v.id}_solid_inner`,position:add(v.position,scale(n,-half))})}
 const faces:MioMeshData['faces']=[];for(const f of mesh.faces){faces.push({id:`${f.id}_solid_outer`,vertexIds:f.vertexIds.map(id=>`${id}_solid_outer`),...(f.materialSlot===undefined?{}:{materialSlot:f.materialSlot})},{id:`${f.id}_solid_inner`,vertexIds:[...f.vertexIds].reverse().map(id=>`${id}_solid_inner`),...(f.materialSlot===undefined?{}:{materialSlot:f.materialSlot})})}
 const faceById=new Map(mesh.faces.map(f=>[f.id,f]));for(const e of deriveMeshEdges(mesh).filter(e=>e.faceIds.length===1)){const source=faceById.get(e.faceIds[0])!,a=e.vertexIds[0],b=e.vertexIds[1];let forward=false;for(let i=0;i<source.vertexIds.length;i++)if(source.vertexIds[i]===a&&source.vertexIds[(i+1)%source.vertexIds.length]===b)forward=true;const x=forward?a:b,y=forward?b:a;faces.push({id:`${e.id}_solid_wall`,vertexIds:[`${y}_solid_outer`,`${x}_solid_outer`,`${x}_solid_inner`,`${y}_solid_inner`],...(source.materialSlot===undefined?{}:{materialSlot:source.materialSlot})})}
 const result={vertices,faces};const final=validateMeshTopology(result),fd=diagnoseMeshTopology(result);if(!final.valid||fd.boundaryEdgeIds.length||fd.nonManifoldEdgeIds.length||fd.inconsistentWindingEdgeIds.length||fd.zeroAreaFaceIds.length)throw new Error(`Solidify produced unsafe topology: boundary=${fd.boundaryEdgeIds.length} nonmanifold=${fd.nonManifoldEdgeIds.length} winding=${fd.inconsistentWindingEdgeIds.length} zero=${fd.zeroAreaFaceIds.length}`);return result;
};
