import { PolicyEngine } from '../security/PolicyEngine';
import { PermissionEngine } from '../security/PermissionEngine';
import { eventBus } from '../core/EventBus';
import { emergencyStop } from '../core/EmergencyStop';
import { MioSystemMode } from '../types/core';
import { ModelRouter } from './ModelRouter';

export interface StructuredAgentResponse {
  understanding: string;
  plan: string[];
  permissionStatus: string;
  executionSummary: string;
  validationStatus: string;
  resultText: string;
  nextSteps: string[];
  suggestedMode?: MioSystemMode;
  emotionalContext?: string;
  provider?: string;
}

export class AgentOrchestrator {
  public static async processPrompt(prompt: string): Promise<StructuredAgentResponse> {
    if (emergencyStop.isEmergencyStopped()) return { understanding: 'System is under EMERGENCY STOP.', plan: [], permissionStatus: 'BLOCKED', executionSummary: 'Execution aborted.', validationStatus: 'FAILED', resultText: 'All operations are suspended until Emergency Stop is reset.', nextSteps: ['Reset Emergency Stop'] };
    eventBus.emit('CORE_STATE_CHANGE', 'THINKING');

    const policyCheck = PolicyEngine.validateInstruction(prompt);
    if (!policyCheck.allowed) {
      eventBus.emit('CORE_STATE_CHANGE', 'ERROR');
      return { understanding: 'Instruction safety inspection failed.', plan: ['Deny execution'], permissionStatus: 'REJECTED_BY_POLICY', executionSummary: 'Blocked by Policy Engine.', validationStatus: 'FAILED', resultText: policyCheck.reason || 'Operation rejected.', nextSteps: ['Revise the request'] };
    }

    const lower = prompt.toLowerCase();
    let suggestedMode: MioSystemMode = 'CHAT';
    if (/search|research|find info|documentation/.test(lower)) suggestedMode = 'RESEARCH';
    else if (/file|organize|directory|duplicate/.test(lower)) suggestedMode = 'FILES';
    else if (/motion|pose|camera|gesture/.test(lower)) suggestedMode = 'MOTION';
    else if (/3d|mesh|model|geometry/.test(lower)) suggestedMode = '3D';
    else if (/animat|keyframe|motion path/.test(lower)) suggestedMode = 'ANIMATION';
    else if (/poster|graphic|layer|vector|typography/.test(lower)) suggestedMode = 'GRAPHIC';
    else if (/sfx|sound effect|synth sound|laser sound/.test(lower)) suggestedMode = 'SFX';
    else if (/music|piano|compose|melody|bpm/.test(lower)) suggestedMode = 'MUSIC';
    else if (/security|permission|audit/.test(lower)) suggestedMode = 'SECURITY';

    const isSensitive = /delete|overwrite|wipe|publish|upload|network|camera|microphone/.test(lower);
    if (isSensitive) {
      const approved = await PermissionEngine.requestPermission({ action: 'SENSITIVE_TASK_EXECUTION', target: 'System / Workspace', level: 'L5_DESTRUCTIVE', changes: ['Potential privileged operation'], risks: ['May affect files, network, or device permissions'], expectedResult: 'Proceed only after explicit authorization' });
      if (!approved) return { understanding: `Sensitive request: "${prompt}"`, plan: ['Require explicit authorization'], permissionStatus: 'REJECTED_BY_USER', executionSummary: 'No privileged operation was executed.', validationStatus: 'ABORTED', resultText: 'The requested action was cancelled or timed out.', nextSteps: ['Approve only if you intend to proceed'], suggestedMode };
    }

    eventBus.emit('CORE_STATE_CHANGE', 'PROCESSING');
    const routed = await ModelRouter.generate(prompt);
    if (!routed.success) {
      eventBus.emit('CORE_STATE_CHANGE', 'ERROR');
      return { understanding: `Analyzed directive: "${prompt}"`, plan: [`Route to ${suggestedMode}`, 'Invoke configured AI provider'], permissionStatus: 'AUTHORIZED', executionSummary: `Provider ${routed.provider} failed.`, validationStatus: 'FAILED', resultText: `AI provider error: ${routed.error || 'unknown error'}`, nextSteps: ['Open Settings and test the provider connection'], suggestedMode, provider: routed.provider };
    }

    eventBus.emit('CORE_STATE_CHANGE', 'SUCCESS');
    setTimeout(() => { if (!emergencyStop.isEmergencyStopped()) eventBus.emit('CORE_STATE_CHANGE', 'IDLE'); }, 1200);
    return {
      understanding: `Analyzed directive: "${prompt}"`,
      plan: ['Validate instruction safety', `Route workflow to ${suggestedMode}`, `Use provider ${routed.provider}`],
      permissionStatus: 'AUTHORIZED',
      executionSummary: routed.provider === 'local_heuristic' ? 'No external model was invoked.' : `Response generated by configured provider ${routed.provider}.`,
      validationStatus: routed.provider === 'local_heuristic' ? 'LOCAL_ONLY' : 'PROVIDER_RESPONSE_RECEIVED',
      resultText: routed.text,
      nextSteps: suggestedMode === 'CHAT' ? [] : [`Open ${suggestedMode} workspace for native tooling`],
      suggestedMode,
      provider: routed.provider,
    };
  }
}
